OSS Fuzz Integration (#607)
* Initial push

* Bump cibuildwheel to 2.19.0

* Change QPDF to qpdf

Refer to the qpdf project and library in lower-case, even at the start of
sentences.

* Fix tests with Python 3.13

The exception message changed to:
```
property '' of 'Page' object has no deleter
```

* Use cibuildwheel 2.19.1; enable Python 3.13 pre-release

* Improve Python 3.13 build settings

* Remove ttk from 3.13

* Add missing return type for PageList.Extend

Closes #592

* Update cibuildwheel to 2.19.1

* Reconcile mtime/permissions when using Pdf.save()

Fixes #595

* Fix Windows quirk in tests

* Prevent leaking an opened file if we open the file but fail to read it as Pdf

* jbig2 handle invalid version

* docs: rewrite .open(), improve .save()

* v9.1.0 release notes

* Bump version: v9.1.0

* Change 'typer[all]' to 'typer' based on upstream changes

* Bump cibuildwheel to v2.20.0

* Update build settings for CPython 3.13

* Fix several unused variable warnings on MSVC

* Fix false positive warning on MSVC

* Use decimal.localcontext for decimal precision

* Suppress scientific notation in saving real numbers to PDF

* v9.1.1 release notes

* Bump version: v9.1.1

* Revert "Use decimal.localcontext for decimal precision"

This reverts commit e05b9021d8d84ebbf0344e76ad1df9ae782c387f.

* Improve handling of CalRGB/CalGray palette images

* Temporarily blacklist setuptools 72 since it seems to prevent build of pp3.9

Error is:
     File "/tmp/build-env-xb6cqppy/lib/pypy3.9/site-packages/setuptools/_distutils/unixccompiler.py", line 268, in link
      linker = (
  TypeError: 'NoneType' object is not subscriptable (key slice(None, None, None))

Unclear if this is due to pybind11 needing an adjustment for setuptools 72
https://github.com/pypa/setuptools/blob/main/NEWS.rst
or cibuildwheel needs something patched.

* Fix __array__ when numpy 2.1+ is present

* Add missing `#include <string>` to utils.h

src/core/utils.h uses symbols defined in `<string>`, but does not
include the header.

This was detected and fixed by engineers applying Bazel's
[`parse_headers`][1] feature to open-source code used at Google, and
we'd like to contribute the fix.

[1]: https://bazel.build/docs/bazel-and-cpp#toolchain-features

* v9.1.2 release notes

* Bump version: v9.1.2

* Avoid using setuptools 72+ on PyPy it breaks the build

Merge branch 'setuptools-issue'

* Modernize SPDX format

* Modernize pybind11 initialization of custom exceptions

Fixes some possible undefined behavior on destruction, etc.

* Update QPDF target version to 11.9.1

* v9.2.0 release notes

* remove EndOfLine as Prerequisite for CCITTFaxDecode

fixes #601

* Bump version: v9.2.0

* Remove wheel as a requirement (probably unnecessary with modern setuptools)

* Fix Rectangle inconsistencies

-Allow Rectangle(Array([0,0,0,0]))
-Allow Rectangle(other_rectangle)

Fixes #605

* Change conditions when test are skipped to prepare for free-threading

* Try building with free thread support (continue on failure)

* v9.2.1 release notes

* Bump version: v9.2.1

* Use sigstore for release

* Set version to 9.2.1rc1

* Iteration testing build.sh

* Install requirements.txt for atheris

* Add -r

* Implement fuzz build process with native extension

* Added cifuzz.yml for pipeline integration

* Removed extraneous corpora

* Removed extraneous requirements.txt from fuzzing directory

* updated formatting

* Appeasing mypy

---------

Co-authored-by: James R. Barlow <james@purplerock.ca>
Co-authored-by: m-holger <m-holger@kubitscheck.org>
Co-authored-by: Elliott Sales de Andrade <quantum.analyst@gmail.com>
Co-authored-by: James Barlow <james@purlerock.ca>
Co-authored-by: Will Angley <willangley@google.com>
Co-authored-by: Leon Eckardt <36102288+ekordas@users.noreply.github.com>
Co-authored-by: bcapuano <bcapuano@asu.edu>
Co-authored-by: Bailey Capuano <32396237+capuanob@users.noreply.github.com>