Temporarily blacklist setuptools 72 since it seems to prevent build of pp3.9
Error is:
     File "/tmp/build-env-xb6cqppy/lib/pypy3.9/site-packages/setuptools/_distutils/unixccompiler.py", line 268, in link
      linker = (
  TypeError: 'NoneType' object is not subscriptable (key slice(None, None, None))

Unclear if this is due to pybind11 needing an adjustment for setuptools 72
https://github.com/pypa/setuptools/blob/main/NEWS.rst
or cibuildwheel needs something patched.